### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mlotfi2005** [ansrivas/angular2-flask#10]
Hi,

I started the backend with no problem, but when I started the front with 
 npm run server:dev:hmr

I got this error 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\alotfi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'server:dev:hmr' ]
2 info using npm@3.10.7
3 info using node@v4.6.1
4 verbose run-script [ 'preserver:dev:hmr', 'server:dev:hmr', 'postserver:dev:hmr' ]
5 info lifecycle angular2-webpack-starter@5.1.1~preserver:dev:hmr: angular2-webpack-starter@5.1.1
6 silly lifecycle angular2-webpack-starter@5.1.1~preserver:dev:hmr: no script for preserver:dev:hmr, continuing
7 info lifecycle angular2-webpack-starter@5.1.1~server:dev:hmr: angular2-webpack-starter@5.1.1
8 verbose lifecycle angular2-webpack-starter@5.1.1~server:dev:hmr: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-webpack-starter@5.1.1~server:dev:hmr: PATH: C:\Users\alotfi\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\alotfi\mProjects\angular2Projects\angular2-flask\front\node_modules\.bin;C:\Users\alotfi\Desktop\myTools\cmder\bin;C:\Users\alotfi\Desktop\myTools\cmder\vendor\git-for-windows\cmd;C:\Users\alotfi\Desktop\myTools\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\alotfi\Desktop\myTools\cmder\vendor\conemu-maximus5;C:\Users\alotfi\Desktop\myTools\cmder\vendor\conemu-maximus5\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\Oracle11g_client\product\11.2.0\client_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Novell\ZENworks\bin;C:\Program Files (x86)\Hyland\Web ActiveX\;C:\Program Files (x86)\Common Files\EMC\;C:\Program Files\Java\jdk1.8.0_91\bin;C:\Python27;C:\Vagrant\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Sublime Text 3\;C:\Users\alotfi\AppData\Local\atom\bin;C:\Users\alotfi\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Users\alotfi\AppData\Roaming\npm;C:\Users\alotfi\Desktop\myTools\cmder\vendor\git-for-windows\usr\bin;C:\Users\alotfi\Desktop\myTools\cmder\vendor\git-for-windows\usr\share\vim\vim74;C:\Users\alotfi\Desktop\myTools\cmder\
10 verbose lifecycle angular2-webpack-starter@5.1.1~server:dev:hmr: CWD: C:\Users\alotfi\mProjects\angular2Projects\angular2-flask\front
11 silly lifecycle angular2-webpack-starter@5.1.1~server:dev:hmr: Args: [ '/d /s /c', 'npm run server:dev -- --inline --hot' ]
12 silly lifecycle angular2-webpack-starter@5.1.1~server:dev:hmr: Returned: code: 1  signal: null
13 info lifecycle angular2-webpack-starter@5.1.1~server:dev:hmr: Failed to exec server:dev:hmr script
14 verbose stack Error: angular2-webpack-starter@5.1.1 server:dev:hmr: `npm run server:dev -- --inline --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\alotfi\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\alotfi\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-webpack-starter@5.1.1
16 verbose cwd C:\Users\alotfi\mProjects\angular2Projects\angular2-flask\front
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alotfi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "server:dev:hmr"
19 error node v4.6.1
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error angular2-webpack-starter@5.1.1 server:dev:hmr: `npm run server:dev -- --inline --hot`
22 error Exit status 1
23 error Failed at the angular2-webpack-starter@5.1.1 server:dev:hmr script 'npm run server:dev -- --inline --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-webpack-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server:dev -- --inline --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-webpack-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-webpack-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ansrivas** [comment]
This was due to a beta release of webpack. May be you can try and test it now.

**Comment by mlotfi2005** [comment]
Hi, thanks for replying, did you mean I should clone your code again and try it or just update something in the code ?
Thanks.

**Comment by ansrivas** [comment]
yes I have pushed a few changes, you can clone it and try it again.

**Comment by mlotfi2005** [comment]
Thank you , it's working now.
