### ISSUE TITLE
Cannot find module 'assets-webpack-plugin'

### ISSUE THREAD

**Issue by ellandebasque** [ansrivas/angular2-flask#11]
Hello,
I would like to try your solution.
I have done all step for the installation. But I have a problem. Can you help me please.

[npm-debug.log.zip](https://github.com/ansrivas/angular2-flask/files/763965/npm-debug.log.zip)

Best regards.

When I run this command : npm run server:dev:hmr
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server:dev" "--" "--inline" "--hot"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.1.1 server:dev: `webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/ "--inline" "--hot"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-webpack-starter@5.1.1 server:dev script 'webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/ "--inline" "--hot"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

For  "sudo npm install webpack-dev-server rimraf webpack typescript -g" command : /usr/local/lib
├── rimraf@2.5.4 
├── typescript@2.1.6 
├── webpack@2.2.1 
└── webpack-dev-server@2.3.0

But for npm install :
front
├─┬ exports-loader@0.6.3
│ └─┬ source-map@0.1.43
│   └── amdefine@1.0.1 
├─┬ imports-loader@0.6.5
│ └─┬ source-map@0.1.43
│   └── amdefine@1.0.1 
├─┬ protractor@4.0.14
│ ├── adm-zip@0.4.7 
│ └─┬ selenium-webdriver@2.53.3
│   └── adm-zip@0.4.4 
├─┬ rimraf@2.5.4
│ └─┬ glob@7.1.1
│   ├── fs.realpath@1.0.0 
│   ├── inflight@1.0.6 
│   └── once@1.4.0 
├─┬ UNMET PEER DEPENDENCY webpack@2.1.0-beta.27
│ └─┬ yargs@6.6.0
│   └── string-width@1.0.2 
└─┬ webpack-dev-server@2.1.0-beta.11
  └─┬ yargs@6.6.0
    ├─┬ cliui@3.2.0
    │ ├── string-width@1.0.2 
    │ └── wrap-ansi@2.1.0 
    ├── get-caller-file@1.0.2 
    ├── os-locale@1.4.0 
    ├── require-directory@2.1.1 
    ├── require-main-filename@1.0.1 
    ├── set-blocking@2.0.0 
    ├── string-width@1.0.2 
    ├── which-module@1.0.0 
    ├── y18n@3.2.1 
    └── yargs-parser@4.2.1

**Comment by ansrivas** [comment]
Hi @ellandebasque,

can you please try the following: 
```
$ npm install -g npm@latest 
$ rm -rf node_modules        
$ npm install
$ npm run server:dev:hmr
```

**Comment by ellandebasque** [comment]
Thank you to answer me,
it's not working I have exactly the same error :(

2017-02-09 17:19 GMT+01:00 Ankur Srivastava <notifications@github.com>:

**Comment by ansrivas** [comment]
I am not able to reproduce this issue locally.
You can try to install it externally:
 `npm install assets-webpack-plugin`

**Comment by ellandebasque** [comment]
It's the same.

I'm trying to install on Windows now but at this time I have the same
problem.

I really do not understand.

2017-02-09 23:47 GMT+01:00 Ankur Srivastava <notifications@github.com>:

**Comment by ansrivas** [comment]
Hi @ellandebasque ,
in case you are still interested to try this, there have been several commits since you last opened this issue. May be you can go ahead and try again,

**Comment by ellandebasque** [comment]
:)

Nice

2017-09-14 1:01 GMT+02:00 Ankur Srivastava <notifications@github.com>:
