### ISSUE TITLE
No module named pylogging

### ISSUE THREAD

**Issue by SRoadknight** [ansrivas/angular2-flask#14]
I followed the process for getting up and running. 

The pylogging module **is** installing when I run $ sudo pip install -r requirements.txt 

However when I run python run.py I am getting the error "No module named pylogging". I'm not quite sure if this is an issue on my end or an issue with the files.

**Comment by ansrivas** [comment]
Hi, 
Can you try to install the pylogging module separately? 

`pip install git+https://github.com/ansrivas/pylogging.git --upgrade`

**Comment by SRoadknight** [comment]
Hi,

I tried installing the pylogging module separately, I had no luck doing it
this way and recieved the same error.

I then set out to follow the process again, however this time doing it in a
virtual env. It worked within the virtual env.
