### ISSUE TITLE
In the frontend, where is it specifying the backend's URL?

### ISSUE THREAD

**Issue by fernandocamargoti** [ansrivas/angular2-flask#18]
I'm using your application as example to develop a Flask+Angular2. I understood why you're running Angular apart from the Flask, but I couldn't find where you're setting the backend URL in development. I mean, the IP:PORT. Is there any configuration file I couldn't find? In production, I've seen the nginx will handle it. But how does it work in development?

**Comment by ansrivas** [comment]
Hi, 
its defined here in webpack.dev.js file.

https://github.com/ansrivas/angular2-flask/blob/master/front/config/webpack.dev.js#L247
