### ISSUE TITLE
Containers on AWS - Elastic Beanstalk - Dockerrun.aws.json

### ISSUE THREAD

**Issue by cmh234** [ansrivas/angular2-flask#19]
I love this app. trying to load on the containers on AWS - Elastic Beanstalk. Every time I load and install the  Dockerrun.aws.json. keep changing the Dockerrun.aws.json with different errors. Now I'm getting this error
"Encountered error starting new ECS task: { "failures": [ { "reason": "RESOURCE:MEMORY", "arn": "arn:aws:ecs:us-west-2:016511600475:container-instance/cc20f5bf-7349-48c7-94a3-512df68b9962" } ], "tasks": [] }"

does anyone know the correct configuration for Dockerrun.aws.json.  This is what i have now

{
    "AWSEBDockerrunVersion": 2,
    "volumes": [
        {
            "name": "backend-v"
        },
        {
            "name": "frontend-v"
        }
    ],
    "containerDefinitions": [
        {
            "name": "backend-c",
            "image": ".dkr.ecr.us-west-2.amazonaws.com/apptbot/server",
            "essential": true,
            "memory": 4096,
            "mountPoints": [
                {
                  "sourceVolume": "backend-v",
                  "containerPath": "/usr/src/app/backend",
                  "readOnly": true
                }
            ]
        },
        {
            "name": "frontend-c",
            "image": ".dkr.ecr.us-west-2.amazonaws.com/apptbot/frontend",
            "essential": true,
            "portMappings": [
                {
                    "hostPort": 3000,
                    "containerPort": 80
                }
            ],
            "links": [
                "backend-c"
            ],
            "mountPoints": [
                {
                    "sourceVolume": "frontend-v",
                    "containerPath": "/var/www/front"
                }
            ],
            "memory": 4096
        }
    ]
}

**Comment by ansrivas** [comment]
Hi, it seems like you are trying to allocate 4096 x 2  ( `"memory": 4096` part ) memory for this configuration. Does you instance have this much available? 
You can try to start with something smaller like 128 and see if you still get the containers up and running.

**Comment by cmh234** [comment]
I reduced the memory to 100 and got past that error. Now I stuck on this error.

**Comment by ansrivas** [comment]
Again it seems like authorization issue:  
1. The image needs to be built and published to the ec2 registry. 
2. If it's available there, do you have a read access to pull the image to your current instance where you are running the containers?

**Comment by cmh234** [comment]
Thank you. I did build the image and successfully tested the containers locally.
I loaded them up to the AWS ec2 registry with Docker push. Verified they are there.
I believe the problem is I need to add this security this action "ecr:GetAuthorizationToken" to the Repository permissions. I cannot find a way to add it through the web interface. for several hours I've tried this technique using AWS ect “http://blog.shippable.com/setting-permissions-on-aws-ec2-ecr-repositories.”

No matter what data I put in the JSON file usr1Policy.json (see attached) 
[usr1Policy.json.txt](https://github.com/ansrivas/angular2-flask/files/1236912/usr1Policy.json.txt)

I ALWAYS get this error. 
An error occurred (InvalidParameterException) when calling the SetRepositoryPolicy operation: Invalid parameter at 'PolicyText' failed to satisfy constraint: 'Invalid repository policy provided'

Any ideas how I get around this error or any other way to add "ecr:GetAuthorizationToken" to the Repository permissions.

**Comment by ansrivas** [comment]
Unfortunately its hard to debug it without logs. The request data for PolicyText doesn't seems to be working. 
It would resolve much easier if you check on stack-overflow (put debug logs) as this is very AWS specific issue.

**Comment by cmh234** [comment]
Thank you. I was able to set ecr:GetAuthorizationTokenin in the EB role and on the registry using a different user.

I'm getting this error on container frontend-c 

host not found in upstream "backend-s" in /etc/nginx/nginx.conf:12
nginx: [emerg] host not found in upstream "backend-s" in /etc/nginx/nginx.conf:12

Do you know how I correctly define the host for AWS container?

**Comment by ansrivas** [comment]
Can you try with the service name in `nginx.conf` rather than using `backend-s` change it to `backend-c` ?

**Comment by cmh234** [comment]
Update:  I opened a ticket with AWS support. I will let you know the solution once we get it working.

**Comment by cmh234** [comment]
I was able to successfully launch the app on AWS Elastic Beanstalk multi containers using this Dockerrun.aws.json

{
    "AWSEBDockerrunVersion": 2,
    "containerDefinitions": [
        {
            "name": "backend-s",
            "image": "YOUR_IMAGE_HERE",
            "essential": true,
            "memory": 400
        },
        {
            "name": "frontend-s",
            "image": "YOUR_IMAGE_HERE",
            "essential": true,
            "portMappings": [
                {
                    "hostPort": 80,
                    "containerPort": 80
                }
            ],
            "links": [
                "backend-s"
            ],
            "memory": 200
        }
    ]
}
