### ISSUE TITLE
Trying to decode jwt token

### ISSUE THREAD

**Issue by gbonline** [ansrivas/angular2-flask#29]
Hi
I'm trying your demo, to decode the jwt token with a simple code but I get an error:
where in AuthenticationService there is the TODO
`//TODO: Decode token and get expiry time from here, someone has to implement this. :(`
before that function, I added a new function :
```
  public decodeJwtToken(token): any {
      let playload = JSON.parse(atob(token.split('.')[1]));
      // console.log(JSON.stringify(playload));
      return playload;
  }
```
and after the TODO line I've added
`let decoded = this.decodeJwtToken(token);`
then when I try to login o got a "Server error" message, but in chrome console I get
```
this.decodeJwtToken is not a function
webpackJsonpac__name_.34.AuthenticationService.handleError @ authentication.service.ts:120
```
I'm new on angular and webpack.
So I ask you what I need to do to resolve the issue?

thanks
Giorgio

**Comment by ansrivas** [comment]
Hi @gbonline,
since this is one liner, can you please try to move it just below the `//TODO: ...` rather than a function call.
 
  ```private extractToken(res: Response) {
    let body = res.json();
    if (res.status === 200) {
      let response = 'response';
      let tokenString = 'jwt';
      let token = body[tokenString];
      //TODO: Decode token and get expiry time from here, someone has to implement this. :(
      let playload = JSON.parse(atob(token.split('.')[1]));
      console.log(JSON.stringify(playload));
      let expiry = new Date(body['exp']);
      let maxTokenExpiryTime = expiry.getTime();
      localStorage.setItem('token', token);
      localStorage.setItem('exp', String(maxTokenExpiryTime));
    }
  }
```

**Comment by gbonline** [comment]
Thanks for answer.
I just tried this solution.
I realized that the error is due to the fact that the function `private extractToken(res: Response) `
is called as the map function from 
```
  public login(body: object) {
    return this.http.post('/api/login', body, jsonHeader())
      .map(this.extractToken)
      .catch(this.handleError);
  }
```
and in that manner the `this ` reference is different in the map scope compared with the AutenticationService scope.
best regards
Giorgio

**Comment by ansrivas** [comment]
Great, indeed that was a scope issue. 
If it works for you, can you close the issue?
