### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by mkscala** [ansrivas/angular2-flask#3]
Are you planning for a Docker Support this APP?

**Comment by ansrivas** [comment]
I am actually already working on it, will soon merge it to the master branch.

**Comment by ansrivas** [comment]
I merged changes to master, related to docker

**Comment by mkscala** [comment]
I will test it today. Thanks for the quick turnaround

**Comment by mkscala** [comment]
The python backed flask runs on alpine linux ? because the other images are pretty heavily loaded.
Is it possible to add the alpine linux support ?

**Comment by mkscala** [comment]
I checked the Dockerfile and I see alpine

**Comment by mkscala** [comment]
I get the below error with docker-compose up
 `-- webpack-core@0.6.8
    +-- source-list-map@0.1.6
    `-- source-map@0.4.4
      `-- amdefine@1.0.0

npm WARN optional Skipping failed optional dependency /webpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6

npm ERR! shasum check failed for /tmp/npm-28-685c270f/registry.npmjs.org/selenium-webdriver/-/selenium-webdriver-2.52.0.tgz
npm ERR! Expected: d2dcb2f51b48733d6c42829e52767ecee2bf4b6b
npm ERR! Actual:   c9913ce4c5209c15097b5f593172c12c44bd3ef2
npm ERR! From:     https://registry.npmjs.org/selenium-webdriver/-/selenium-webdriver-2.52.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /front/npm-debug.log
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c npm install rimraf webpack typescript -g   && npm install   && npm run build:prod   && chown -R app:app /front' returned a non-zero code: 1

**Comment by mkscala** [comment]
I have node and npm version on ubuntu
node v6.4.0
 npm  v3.10.6

**Comment by ansrivas** [comment]
This is quite weird as it works perfectly with the same node and npm version on my docker. 
Can you try to run the frontend, the regular way, as it is explained in Readme ( not the docker version )
