### ISSUE TITLE
Cannot  run on production mode

### ISSUE THREAD

**Issue by gbonline** [ansrivas/angular2-flask#30]
Hi, I'm developing a little app up on this Angular app. I'm new with angular and his ecosystem...
I builded my app for production with command 
`npm run build:prod`
and then I would like to serve as prod, but with 
`npm run server:prod`
I get an error:
```
iMacGiorgio:front nemesix$ npm run server:prod

> angular-starter@6.0.0 server:prod /Users/nemesix/Sviluppo/prove/angular2-flask-master/front
> http-server dist -c-1 --cors

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server:prod"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-starter@6.0.0 server:prod: `http-server dist -c-1 --cors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-starter@6.0.0 server:prod script 'http-server dist -c-1 --cors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server dist -c-1 --cors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nemesix/Sviluppo/prove/angular2-flask-master/front/npm-debug.log
```
so I tried the following
`npm run server:prod:ci`
and this show me the valid addresses as http://<< IP >>:3000
and in the browser I can see the login page, but the backend server can not be reached.
```
[Wed Oct 11 2017 19:06:54 GMT+0200 (CEST)] "POST /api/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML,like Gecko) Chrome/61.0.3163.100 Safari/537.36"
[Wed Oct 11 2017 19:06:54 GMT+0200 (CEST)] "POST /api/login" Error (404): "Not found"
[Wed Oct 11 2017 19:06:54 GMT+0200 (CEST)] "POST /api/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML,like Gecko) Chrome/61.0.3163.100 Safari/537.36"
[Wed Oct 11 2017 19:06:54 GMT+0200 (CEST)] "POST /api/login" Error (404): "Not found"
```
I left the backend as localhost:8080,
I ask you kindly what I can do to run the app
thanks in advance
Regards
Giorgio

**Comment by ansrivas** [comment]
Hi @gbonline , 

As you see its a port conflict:
`Error: listen EADDRINUSE 0.0.0.0:8080`

1. You can change the port number to `5000` in this file:
https://github.com/ansrivas/angular2-flask/blob/1fcc48e16059cc265d0ff157818b07bdfa870b60/front/config/webpack.prod.js#L26
2. Run `npm run server:prod` in one of the terminals.
3. Execute `python run.py` in other terminal. 

Let me know if this works for you.

**Comment by gbonline** [comment]
Hi Ansrivas
Thanks a lot for the suggestion. Now the app works well.
I'd like to ask you some technical questions about a solution to use for my app.
The app have a free/public page where to show some shop prices, and a reserved area where to manage shops (as crud) and prices. The problem is how to show real-time prices changes!
Now I've used a socketio client on frontent angular app and a socketio server on the backend python app. But I think this is too sophisticated for the purpose.
Previously I had used a rxjs Subject / subscribe system on the WebService service: but when I show the public page on a different browser/client I cant get the subscribed values. 
It's possible to use the Subject / subscribe solution for different clients? 
In your app there is a native web server, it's possible to use this for client communications?
thanks
regards
Giorgio

**Comment by ansrivas** [comment]
Hi @gbonline , 

This is more of a design question and out of scope of this current app. 
I believe you would get much better answers/suggestions if you post this exact question on StackOverflow. 
As far as this app is concerned, its scope is very limited and it's just an attempt to get quickly started with angular4+flask. Anything beyond that is completely upto the user.

**Comment by gbonline** [comment]
Hi Ansrivas, 
thanks for answer, before asking you for something I had searched for on the net and I've only found solutions with socketio or similar, but given my inexperience with angular I considered your expertise to be able to get a better answer.

I would have another question but this time on the app: how do you use the App State to monitor and eventually limit users to just one login at a time?

thanks for your patience
regards
Giorgio

**Comment by ansrivas** [comment]
Hi @gbonline , 

I recommended StackOverflow because you will have a wider audience who could solve your confusions with definitely much better solutions/ideas.

Coming to your current question:
I am not very sure about the idea of using App State to limit user login i.e. on the frontend side.

Rather store sessions in the backend and return the same session/state if the user has been previously logged in.
There are several flask extensions to achieve this, Flask-security, Flask-sessions, Flask-Login, etc.
