### ISSUE TITLE
I get some SSL error

### ISSUE THREAD

**Issue by mkscala** [ansrivas/angular2-flask#4]
Successfully installed Flask-0.11.1 Flask-Cors-2.1.2 Flask-Login-0.3.2 Flask-Mail-0.9.1 Flask-Principal-0.4.0 Flask-SQLAlchemy-2.1 Flask-Security-1.7.5 Flask-WTF-0.12 Jinja2-2.8 MarkupSafe-0.23 SQLAlchemy-1.0.14 WTForms-2.1 Werkzeug-0.11.10 blinker-1.4 click-6.6 gevent-1.1.2 greenlet-0.4.10 itsdangerous-0.24 passlib-1.6.5
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by ansrivas** [comment]
Its a `requests` related issue, you can try this solution on stackoverflow.

[http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent](http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent)
