### ISSUE TITLE
angular2-jwt

### ISSUE THREAD

**Issue by mkscala** [ansrivas/angular2-flask#8]
Is it possible to add angular2-jwt Auth0?
https://medium.com/@blacksonic86/angular-2-authentication-revisited-611bf7373bf9#.ut4n3xu78

**Comment by shantanoo-desai** [comment]
Maybe this simple backend implementation module might help [Flask-Simple-JWT](http://flask-jwt-simple.readthedocs.io/en/latest/index.html)

**Comment by ansrivas** [comment]
@shantanoo-desai thanks for the link, I found sometime and started the implementation. Should be completed soon.

**Comment by shantanoo-desai** [comment]
I actually tried it out yesterday and I can access a protected API with the JWT token. For this repo it makes sense to use `flask-simple-jwt` for complex ones there is some extended library

**Comment by ansrivas** [comment]
https://github.com/ansrivas/angular2-flask/tree/0.2.0 implements this. I have also created an automated build with dockerhub. 
You can test it from master already.

**Comment by shantanoo-desai** [comment]
If we are in sync with what you are doing for the next __TODO__ then we might need `angular2-jwt` node module on the frontend and then use `JWT_EXPIRES` time from the server?
(I mean in terms of token expiry on the frontend and session management)

**Comment by ansrivas** [comment]
Yes, indeed that's the next step. But due to lack of time, I will put it on hold. Feel free to send a pull request though.

**Comment by shantanoo-desai** [comment]
👍 Same here. Maybe on the weekend I might look into it.
