### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by addl** [ansrivas/angular2-flask#9]
Apologize me, because of this is not a bug, it's only a question. I am new in Angular 2 and NodeJS, but not in Flask. Why do you need start two server?. It's not enough just the Flask server?. I have understood that the Angular 2 and other .ts files are compiled and then retrieve en Jinja templates as normal .js files. i am wrong??. Please, I would appreciate your help. Thanks!!!!

**Comment by ansrivas** [comment]
Hi @addl , 
Your assumption is absolutely correct w.r.t Flask, but in current implementation I am just sticking with a random-rest backend which can be called from Angular2. So at some point even if you change your rest service provider (write entire backend in any other language) you are not really dependent on templates, rather you just return jsons and consume it in your frontend application.

Also in an ideal condition its considered a good practice to let nginx serve your static files and forward requests from there to backend server.

**Comment by addl** [comment]
Thanks a lot!!!. I think that on this way there is a great approach  Nevertheless I am not completely sure about what is the best choice, well, I guess it depends on many factors. For example, in case such as build a Web Blog or a Company Intranet. Anyway I just want learn Angular 2 at this time, so for the moment, I will follow your solution. Thanks again.
